
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'john-mayer',
    name: 'Archetype: John Mayer X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: "John Mayer's iconic tone, in one definitive plugin.",
    fullDescription: 'Experience the pure, articulate tones of one of the greatest modern guitarists.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isComingSoon: true,
  },
  {
    id: 'misha-mansoor',
    name: 'Archetype: Misha Mansoor X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'The ultimate toolkit for modern metal guitar, as innovative and uncompromising as Misha himself.',
    fullDescription: 'Designed with the progressive metal pioneer.',
    price: 125,
    image: 'https://images.unsplash.com/photo-1558403194-611308249627?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
    isComingSoon: true,
  },
  {
    id: 'mantra',
    name: 'Mantra',
    category: 'PLUGIN',
    subCategory: 'Vocal',
    shortDescription: 'All the essential tools for modern vocal production in one plugin.',
    fullDescription: 'A complete vocal suite.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1514593214839-ce1849100055?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
  },
  {
    id: 'tim-henson',
    name: 'Archetype: Tim Henson X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'As Tim eloquently put it: this one f**ks.',
    fullDescription: 'Signature tones from Polyphia\'s mastermind.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1516924962500-2b4b3b99ea02?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
    isComingSoon: true,
  },
  {
    id: 'rabea',
    name: 'Archetype: Rabea X',
    category: 'PLUGIN',
    subCategory: 'Synth',
    shortDescription: 'Bringing world-class synth sounds to the modern guitarist.',
    fullDescription: 'The first plugin to feature a complete internal synthesizer.',
    price: 139,
    image: 'https://images.unsplash.com/photo-1593697821028-7cc59cfd7399?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isComingSoon: true,
  },
  {
    id: 'petrucci',
    name: 'Archetype: Petrucci X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'Classy and remarkable, just like the man himself.',
    fullDescription: 'The most complete plugin we have ever made.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isComingSoon: true,
  },
  {
    id: 'cory-wong',
    name: 'Archetype: Cory Wong X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'Designed to offer a wide variety of options for players in search of the perfect clean tones.',
    fullDescription: 'The king of funk tones.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1525201548942-d8b8967d0f5c?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
  },
  {
    id: 'nolly',
    name: 'Archetype: Nolly X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'The purest distillation of Nolly’s custom-modded guitar amp collection.',
    fullDescription: 'Adam "Nolly" Getgood\'s essential amp collection.',
    price: 135,
    image: 'https://images.unsplash.com/photo-1564186763535-ebb21ef52784?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
  },
  {
    id: 'parallax-x',
    name: 'Parallax X',
    category: 'PLUGIN',
    subCategory: 'Bass',
    shortDescription: 'Everything you need to design the ultimate bass tone.',
    fullDescription: 'Parallel processing for bass.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1445375011172-23746ee9840c?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
  },
  {
    id: 'soldano',
    name: 'Soldano SLO-100 X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'The legendary amplifier that originated American high-gain tone.',
    fullDescription: 'Officially licensed Soldano SLO-100.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1541613569553-33232674c377?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  },
  {
    id: 'fortin-nameless',
    name: 'Fortin Nameless Suite X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'Precisely engineered brutality. A legendary amplifier replicated in a beautiful plugin.',
    fullDescription: 'Extreme high gain.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  },
  {
    id: 'gojira',
    name: 'Archetype: Gojira X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'The heaviest plugin in the universe.',
    fullDescription: 'From Joe Duplantier of Gojira.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
    isBestseller: true,
  },
  {
    id: 'plini',
    name: 'Archetype: Plini X',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'A truly versatile plugin, elegantly developed with the artist who inspired it.',
    fullDescription: 'The most versatile plugin in our collection.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1459749411177-042180ce673c?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  },
  {
    id: 'morgan-amps',
    name: 'Morgan Amps Suite',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'A legacy of vintage modern amplifiers revered for their warmth and responsiveness.',
    fullDescription: 'Official Morgan Amps simulation.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  },
  {
    id: 'mateus-asato',
    name: 'Archetype: Mateus Asato',
    category: 'PLUGIN',
    subCategory: 'Guitar',
    shortDescription: 'Explore the creative and expressive tones of a modern-day guitar virtuoso.',
    fullDescription: 'Mateus Asato signature suite.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1461784121038-f088ca1e7714?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  },
  {
    id: 'cortex-prime',
    name: 'CORTEX PRIME',
    category: 'HARDWARE',
    shortDescription: 'The most powerful floor modeler on the planet.',
    fullDescription: 'Quad-core SHARC DSP architecture captures the essence of any gear.',
    price: 1849,
    image: 'https://images.unsplash.com/photo-1621112904887-419379ce6824?q=80&w=1000&auto=format&fit=crop',
    isAvailable: true,
  }
];
